@camilaesouza/20/feature/organizations area manager
open-social-care/backend pull request #21
Opened 2024-02-07 23:02 UTC by camilaesouza

# Description

Add functions for organization user manager

## Resume
Add area for organizations maganer

## Changes Made
- Create organization controller with tests (create function to show organization, update and list users by role, based on logged in user manager)

## Related Issues
https://github.com/open-social-care/backend/issues/20

## How to test
Via swegger interface api Manager/Organization

## Observation
This branch was created based on the branch's changes (@camilaesouza/18/feature/organizations-area), because the branch was still under review and files and features needed to be added to it.

## Checklist
- [x] I followed the project's code conventions.
- [x] I have added tests to cover the changes made.
- [x] I have updated the documentation, if necessary.
- [x] This PR has been tested locally and is ready for review.

2024-02-19 19:38 UTC, andresjesse requested changes

2024-02-19 19:38 UTC, andresjesse commented on app/Actions/Manager/Organization/OrganizationUpdateAction.php
> +    public static function execute(OrganizationDTO $dto): void
Como garantir que a Action faz o serviço certo? Seria bom ter teste unitário.

2024-02-19 19:38 UTC, andresjesse commented on app/Http/Controllers/Api/Manager/OrganizationController.php
> +            $organization = $user->organizations->first();
Não entendi por que é usada a primeira organização, tanto faz neste caso? E se um User tiver mais de uma?

2024-02-19 19:38 UTC, andresjesse commented on app/Http/Middleware/OnlyManagerUser.php
> +        if ($user->hasRole(RolesEnum::MANAGER->value) && $user->organizations->isNotEmpty()) {
Caso hipotético:
- Meu user tem role Manager, mas pertence a duas organizações;
- Posso gerenciar apenas uma delas e ser apenas assistente social na outra?

2024-02-29 17:38 UTC, camilaesouza commented on app/Http/Controllers/Api/Manager/OrganizationController.php
> +            $organization = $user->organizations->first();
A gente fez a modelagem para o user ter acesso a mais de uma organização, porém no primeiro momento, concordamos que o usuário teria apenas uma organização, por isso fiz assim. Mas vou alterar para tbm ter o organization_id como parametro

2024-02-29 17:38 UTC, camilaesouza commented on app/Http/Middleware/OnlyManagerUser.php
> +        if ($user->hasRole(RolesEnum::MANAGER->value) && $user->organizations->isNotEmpty()) {
acredito que não tem como. O usuário teria que ter outro acesso ao sistema, pois como ta previsto as permissões com base me perfil, se ele tiver mais de um, vai ter acesso de forma geral, acessos manager e acessos assistente social. Poderia ser feito de forma separada, como um impersonate, onde o usuário escolhe como quer estar atuando se tiver mais de uma role, mas acredito que pra primeiro momento podemos deixar apenas com uma role

2024-03-05 10:35 UTC, andresjesse commented on app/Http/Controllers/Api/Manager/OrganizationController.php
> +            $organization = $user->organizations->first();
Isso, deixar parametrizado agora é mais fácil que refatorar depois.

2024-03-05 10:53 UTC, andresjesse commented on app/Http/Middleware/OnlyManagerUser.php
> +        if ($user->hasRole(RolesEnum::MANAGER->value) && $user->organizations->isNotEmpty()) {
talvez a gente precise mudar aquele relacionamento `organization_user` para permitir isso. Manager de forma global já não vai atender nosso primeiro caso, que é o CCG e o Albergue no mesmo sistema. Vamos discutir esse relacionamento `organizations <-> users` em meet para definir como proceder.

2024-03-06 21:47 UTC, merged