@camilaesouza/22/feature/users area manager
open-social-care/backend pull request #37
Opened 2024-04-11 23:44 UTC by camilaesouza

# Description

- Add user controller for manager role

## Changes Made
- Add UserController for manager
- Add userPolicies

## Related Issues
https://github.com/open-social-care/backend/issues/22

## How to test
1 - Via insomnia: 
- import the file docs/insomnia.json > and test by manager/user

2 - Via swagger 
- access localhost/api/documentation
- Manager/Users > and test 

## Checklist
- [x] I followed the project's code conventions.
- [x] I have added tests to cover the changes made.
- [x] I have updated the documentation, if necessary.
- [x] This PR has been tested locally and is ready for review.

2024-04-16 21:35 UTC, andresjesse requested changes
Senti falta de testes de autorização para as rotas criadas, ex:
- garantir que um manager de outra org não possa acessar a minha org (assertForbidden)
- em geral, garantir que users só acessem recursos das orgs associadas, garantir que não acessem as outras.
- Garantir que o admin acesse tudo (revisar os testes).

Conferir e adequar o comportamento padrão para destroy user:
- um usuário associado à organizações não pode ser excluído. retornar um erro.
- vamos assumir que o processo padrão vai ser: remover ele manualmente de todas as orgs, depois excluir.
- Os testes da Action UserDestroyAction vão ficar bem mais simples (se tiver alguma org, não remove).
- Precisa existir uma rota para um manager remover o user de uma org gerenciada por ele (detach, remover pivos user_id,org_id). Por enquanto só o admin consegue fazer isso via "api/admin/organizations/{organization}/disassociate-users", está ok para o seu TCC, mas é um issue que precisa ser anotado.

2024-04-16 21:35 UTC, andresjesse commented on tests/Feature/Controllers/Api/Manager/UserControllerTest.php
> +    public function testDestroyMethod()
Um teste necessário: 
- criar um user, associar a duas orgs
- tentar excluir o user sem detach das orgs deve retornar um erro.

2024-04-16 21:35 UTC, andresjesse commented on tests/Unit/Actions/Manager/User/UserDestroyActionTest.php
> +    public function testExecuteActionWhenUserHasOnlyOneOrganization()
deveria retornar um erro (impedir a exclusão do user).

2024-04-16 21:35 UTC, andresjesse commented on tests/Unit/Actions/Manager/User/UserDestroyActionTest.php
> +    public function testExecuteActionWhenUserHasMoreThanOneOrganizationAndSameRole()
deveria retornar um erro (impedir a exclusão do user).

2024-04-16 21:35 UTC, andresjesse commented on tests/Unit/Actions/Manager/User/UserDestroyActionTest.php
> +    public function testExecuteActionWhenUserHasMoreThanOneOrganizationAndDifferentRoles()
deveria retornar um erro (impedir a exclusão do user).

2024-04-16 21:35 UTC, andresjesse commented on app/Actions/Manager/User/UserDestroyAction.php
> +    public static function execute(User $user, Organization $organization): void
Mudar o comportamento deste método: se o user possui orgs (com qualquer role), impedir a exclusão.

2024-04-17 21:06 UTC, camilaesouza commented on app/Actions/Manager/User/UserUpdateAction.php
> +        $userData['password'] = ! $userData['password'] ? $user->getAuthPassword() : $userData['password'];
Ele não mantem a antiga professor, ele atualiza para vazio, por isso a logica

2024-04-23 20:41 UTC, andresjesse approved these changes

2024-05-07 23:43 UTC, merged